use std::{env, fs, path::PathBuf};

use cbindgen::{Builder, Config};

const HEADER: &str = "/// Automatically generated by cbindgen. Do not edit directly.";

fn main() {
    println!("cargo:rerun-if-changed=src/");
    println!("cargo:rerun-if-changed=Cargo.toml");
    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed=cbindgen.toml");

    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_dir = env::var("OUT_DIR").unwrap();
    let include_dir = PathBuf::from(&crate_dir).join("include");
    let header_file = PathBuf::from(&out_dir).join("rosu_pp.h");

    fs::create_dir_all(&include_dir).unwrap();

    let config = Config::from_root_or_default(crate_dir.as_str());

    Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .with_header(HEADER)
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file(&header_file);

    fs::copy(&header_file, include_dir.join("rosu_pp.h")).unwrap();

    println!("cargo:include={}", include_dir.display());
}
