/* WARNING: this file was auto-generated by cheadergen from `rosu-pp-ffi`. Do not edit it manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Return code for FFI functions that can fail.
 *
 * Variants:
 * - `Ok` -- Operation succeeded.
 * - `Done` -- Gradual calculator has processed all objects (only returned by
 *   `rosu_pp_gradual_performance_next` and `rosu_pp_gradual_difficulty_next`).
 * - `ParseError` -- Input string could not be parsed (beatmap parsing, mod parsing).
 * - `NullPointer` -- A null pointer was passed where a valid handle was expected.
 * - `InvalidArgument` -- An argument value was out of range or otherwise invalid.
 * - `TooSuspicious` -- The beatmap contains suspicious hit objects that make
 *   calculation unreliable (only returned by `checked_*` functions).
 */
typedef enum rosu_pp_FfiResult {
  rosu_pp_FfiResult_Ok = 0,
  rosu_pp_FfiResult_Done = 1,
  rosu_pp_FfiResult_ParseError = 2,
  rosu_pp_FfiResult_NullPointer = 3,
  rosu_pp_FfiResult_InvalidArgument = 4,
  rosu_pp_FfiResult_TooSuspicious = 5,
  rosu_pp_FfiResult_None = 6,
} rosu_pp_FfiResult;

/**
 * The four osu! game modes.
 *
 * Matches the integer values used by the osu! API:
 * - `Osu` = 0 (osu!standard)
 * - `Taiko` = 1 (osu!taiko)
 * - `Catch` = 2 (osu!catch / fruits)
 * - `Mania` = 3 (osu!mania)
 */
typedef enum rosu_pp_GameMode {
  rosu_pp_GameMode_Osu = 0,
  rosu_pp_GameMode_Taiko = 1,
  rosu_pp_GameMode_Catch = 2,
  rosu_pp_GameMode_Mania = 3,
} rosu_pp_GameMode;

/**
 * Opaque handle to an inspected difficulty calculator.
 *
 * Created via `rosu_pp_difficulty_inspect`. Use getter functions to inspect
 * the configured values.
 */
typedef struct rosu_pp_InspectDifficultyHandle rosu_pp_InspectDifficultyHandle;

/**
 * Opaque handle to a `BeatmapAttributes` result.
 *
 * Created via `rosu_pp_beatmap_attrs_builder_build`. Query it with getter
 * functions and `rosu_pp_beatmap_attrs_hit_windows`.
 *
 * **Must be freed** with `rosu_pp_beatmap_attrs_free` when done.
 */
typedef struct rosu_pp_BeatmapAttributesHandle rosu_pp_BeatmapAttributesHandle;

/**
 * Opaque handle to a `BeatmapAttributesBuilder`.
 *
 * Created via `rosu_pp_beatmap_attrs_builder_new`. Configure it with setter
 * functions, then build with `rosu_pp_beatmap_attrs_builder_build`.
 *
 * **Must be freed** with `rosu_pp_beatmap_attrs_builder_free` when done.
 */
typedef struct rosu_pp_BeatmapAttributesBuilderHandle rosu_pp_BeatmapAttributesBuilderHandle;

/**
 * Opaque handle to a loaded osu! beatmap.
 *
 * Created via `rosu_pp_beatmap_from_path` or `rosu_pp_beatmap_from_bytes`.
 * Must be freed with `rosu_pp_beatmap_free` when no longer needed.
 */
typedef struct rosu_pp_BeatmapHandle rosu_pp_BeatmapHandle;

/**
 * Opaque handle to a gradual difficulty calculator.
 *
 * Created via `rosu_pp_gradual_difficulty_new`. Iterate through hit objects
 * using `rosu_pp_gradual_difficulty_next` until it returns `FfiResult::Done`.
 *
 * **Must be freed** with `rosu_pp_gradual_difficulty_free` when done.
 */
typedef struct rosu_pp_GradualDifficultyHandle rosu_pp_GradualDifficultyHandle;

/**
 * Opaque handle to a gradual performance calculator.
 *
 * Created via `rosu_pp_gradual_performance_new`. Iterate through hit objects
 * using `rosu_pp_gradual_performance_next` until it returns `FfiResult::Done`.
 *
 * **Must be freed** with `rosu_pp_gradual_performance_free` when done.
 */
typedef struct rosu_pp_GradualPerformanceHandle rosu_pp_GradualPerformanceHandle;

/**
 * Opaque handle to a game mods collection.
 *
 * Created via `rosu_pp_mods_parse`, `rosu_pp_mods_parse_with_mode`, or
 * `rosu_pp_mods_from_bits`. Must be freed with `rosu_pp_mods_free`.
 */
typedef struct rosu_pp_ModsHandle rosu_pp_ModsHandle;

/**
 * Opaque handle to a difficulty calculator builder.
 *
 * Created via `rosu_pp_difficulty_new`. Configure it with setter functions,
 * then calculate with `rosu_pp_difficulty_calculate`.
 *
 * **Builder pattern:** Each setter consumes the handle internally and
 * returns `FfiResult::Ok`. The handle pointer remains valid and can be
 * used for subsequent setter calls.
 *
 * **Must be freed** with `rosu_pp_difficulty_free` when done.
 */
typedef struct rosu_pp_DifficultyHandle rosu_pp_DifficultyHandle;

/**
 * Opaque handle to a performance calculator builder.
 *
 * Created via `rosu_pp_performance_new`. Configure it with setter functions,
 * then calculate with `rosu_pp_performance_calculate`.
 *
 * **Builder pattern:** Each setter consumes the handle internally and
 * returns `FfiResult::Ok`. The handle pointer remains valid and can be
 * used for subsequent setter calls.
 *
 * **Lifetime requirement:** The `BeatmapHandle` passed to
 * `rosu_pp_performance_new` **must remain valid for the entire lifetime**
 * of this `PerformanceHandle`. Do NOT free the beatmap handle until after
 * you have called `rosu_pp_performance_free`. Using this handle after the
 * beatmap has been freed results in undefined behavior.
 *
 * **Must be freed** with `rosu_pp_performance_free` when done.
 */
typedef struct rosu_pp_PerformanceHandle rosu_pp_PerformanceHandle;

/**
 * Adjusted beatmap attributes with clock rate applied to AR and OD.
 */
typedef struct rosu_pp_AdjustedBeatmapAttributes {
  /**
   * Approach rate
   */
  double ar;
  /**
   * Circle size
   */
  float cs;
  /**
   * HP drain rate
   */
  float hp;
  /**
   * Overall difficulty
   */
  double od;
} rosu_pp_AdjustedBeatmapAttributes;

/**
 * AR and OD hit windows for a beatmap.
 *
 * Fields populated depend on the game mode (otherwise `NaN`):
 * - **osu! (0):** `ar`, `od_great`, `od_ok`, `od_meh`
 * - **taiko (1):** `od_great`, `od_ok`
 * - **catch (2):** `ar`
 * - **mania (3):** `od_perfect`, `od_great`, `od_good`, `od_ok`, `od_meh`
 */
typedef struct rosu_pp_HitWindows {
  /**
   * Hit window for approach rate (AR) in milliseconds.
   * Only available for osu! and catch.
   */
  double ar;
  /**
   * Perfect hit window (mania only).
   */
  double od_perfect;
  /**
   * Great hit window for OD (osu!, taiko, mania).
   */
  double od_great;
  /**
   * Good hit window (mania only).
   */
  double od_good;
  /**
   * Ok hit window for OD (osu!, taiko, mania).
   */
  double od_ok;
  /**
   * Meh hit window (osu!, mania only).
   */
  double od_meh;
} rosu_pp_HitWindows;

/**
 * The result of calculating the strains on a map.
 *
 * Suitable to plot the difficulty of a map over time. The `mode` field
 * indicates which game mode the strains belong to, and the corresponding
 * strain arrays will be populated. All other arrays will be `nullptr`.
 *
 * **osu! (mode=0):** `aim`, `aim_no_sliders`, `speed`, `flashlight`
 * **taiko (mode=1):** `color`, `reading`, `rhythm`, `stamina`, `single_color_stamina`
 * **catch (mode=2):** `movement`
 * **mania (mode=3):** `strains`
 */
typedef struct rosu_pp_StrainsData {
  /**
   * Game mode: 0=osu!, 1=taiko, 2=catch, 3=mania
   */
  int32_t mode;
  /**
   * Time between two strain values in milliseconds (valid for all modes)
   */
  double section_len;
  /**
   * Number of strain values in each array
   */
  uintptr_t len;
  /**
   * Aim strain peaks (osu! only)
   */
  const double *aim;
  /**
   * Aim strain peaks without sliders (osu! only)
   */
  const double *aim_no_sliders;
  /**
   * Speed strain peaks (osu! only)
   */
  const double *speed;
  /**
   * Flashlight strain peaks (osu! only)
   */
  const double *flashlight;
  /**
   * Stamina strain peaks (taiko only)
   */
  const double *stamina;
  /**
   * Rhythm strain peaks (taiko only)
   */
  const double *rhythm;
  /**
   * Color strain peaks (taiko only)
   */
  const double *color;
  /**
   * Reading strain peaks (taiko only)
   */
  const double *reading;
  /**
   * Single color stamina strain peaks (taiko only)
   */
  const double *single_color_stamina;
  /**
   * Movement strain peaks (catch only)
   */
  const double *movement;
  /**
   * Strain peaks (mania only)
   */
  const double *strains;
} rosu_pp_StrainsData;

/**
 * Hit result counts and score composition for a single play.
 *
 * Initialize with `rosu_pp_score_state_new` and fill in the fields
 * corresponding to the game mode and hit results achieved.
 *
 * **osu! fields:** `max_combo`, `osu_large_tick_hits`, `osu_small_tick_hits`,
 * `slider_end_hits`, `n300`, `n100`, `n50`, `misses`, `legacy_total_score`,
 * `legacy_total_score_valid`
 *
 * **Taiko fields:** `max_combo`, `n300`, `n100`, `n50`, `misses`
 *
 * **Catch fields:** `max_combo`, `n300`, `n100`, `n50`, `n_katu`, `misses`
 *
 * **Mania fields:** `max_combo`, `n_geki`, `n_katu`, `n300`, `n100`, `n50`,
 * `misses`, `legacy_total_score`, `legacy_total_score_valid`
 */
typedef struct rosu_pp_ScoreState {
  /**
   * Maximum combo achieved in the play
   */
  uint32_t max_combo;
  /**
   * Number of large tick (whistle) hits on sliders (osu! only)
   */
  uint32_t osu_large_tick_hits;
  /**
   * Number of small tick (clap) hits on sliders (osu! only)
   */
  uint32_t osu_small_tick_hits;
  /**
   * Number of slider end hits (osu! only)
   */
  uint32_t slider_end_hits;
  /**
   * Number of geki (320) hits (mania only)
   */
  uint32_t n_geki;
  /**
   * Number of katu (200) hits / tiny droplet misses (mania / catch)
   */
  uint32_t n_katu;
  /**
   * Number of 300-score hit results
   */
  uint32_t n300;
  /**
   * Number of 100-score hit results
   */
  uint32_t n100;
  /**
   * Number of 50-score hit results
   */
  uint32_t n50;
  /**
   * Number of misses
   */
  uint32_t misses;
  /**
   * Legacy total score value (osu! only)
   */
  uint32_t legacy_total_score;
  /**
   * Whether `legacy_total_score` is valid (osu! only)
   */
  bool legacy_total_score_valid;
} rosu_pp_ScoreState;

/**
 * Unified difficulty attributes for all osu! game modes.
 *
 * After a difficulty calculation, inspect the `mode` field to determine which
 * attributes are valid:
 *
 * - **`0` (osu!):** `aim`, `speed`, `flashlight`, `ar`, `od`, `hp`,
 *   `great_hit_window`, `ok_hit_window`, `meh_hit_window`, `n_circles`,
 *   `n_sliders`, `n_large_ticks`, `n_spinners`, `aim_difficult_slider_count`,
 *   `slider_factor`, `aim_top_weighted_slider_factor`, `speed_top_weighted_slider_factor`,
 *   `speed_note_count`, `aim_difficult_strain_count`, `speed_difficult_strain_count`,
 *   `nested_score_per_object`, `legacy_score_base_multiplier`, `maximum_legacy_combo_score`
 *
 * - **`1` (taiko):** `stamina`, `rhythm`, `color`, `reading`,
 *   `mono_stamina_factor`, `mechanical_difficulty`, `consistency_factor`
 *
 * - **`2` (catch):** `preempt`, `n_fruits`, `n_droplets`, `n_tiny_droplets`
 *
 * - **`3` (mania):** `n_hold_notes`
 *
 * Fields `stars`, `max_combo`, `is_convert`, and `mode` are valid for all modes.
 */
typedef struct rosu_pp_DifficultyAttributes {
  /**
   * Game mode: 0=osu!, 1=taiko, 2=catch, 3=mania
   */
  int32_t mode;
  /**
   * Star rating (valid for all modes)
   */
  double stars;
  /**
   * Maximum combo (valid for all modes)
   */
  uint32_t max_combo;
  /**
   * Aim difficulty (osu! only)
   */
  double aim;
  /**
   * Speed difficulty (osu! only)
   */
  double speed;
  /**
   * Flashlight difficulty (osu! only)
   */
  double flashlight;
  /**
   * Stamina difficulty (taiko only)
   */
  double stamina;
  /**
   * Rhythm difficulty (taiko only)
   */
  double rhythm;
  /**
   * Color difficulty (taiko only)
   */
  double color;
  /**
   * Reading difficulty (taiko only)
   */
  double reading;
  /**
   * Approach Rate (osu! only)
   */
  double ar;
  /**
   * HP Drain rate (osu! only)
   */
  double hp;
  /**
   * Great hit window in milliseconds (osu! / taiko)
   */
  double great_hit_window;
  /**
   * OK hit window in milliseconds (osu! / taiko)
   */
  double ok_hit_window;
  /**
   * Meh hit window in milliseconds (osu! only)
   */
  double meh_hit_window;
  /**
   * Number of circles (osu! only)
   */
  uint32_t n_circles;
  /**
   * Number of sliders (osu! only)
   */
  uint32_t n_sliders;
  /**
   * Number of large ticks / whistle hits (osu! only)
   */
  uint32_t n_large_ticks;
  /**
   * Number of spinners (osu! only)
   */
  uint32_t n_spinners;
  /**
   * Number of hit objects (mania only)
   */
  uint32_t n_objects;
  /**
   * Number of difficult aim slider strains (osu! only)
   */
  double aim_difficult_slider_count;
  /**
   * Slider factor (osu! only)
   */
  double slider_factor;
  /**
   * Top-weighted aim slider factor (osu! only)
   */
  double aim_top_weighted_slider_factor;
  /**
   * Top-weighted speed slider factor (osu! only)
   */
  double speed_top_weighted_slider_factor;
  /**
   * Speed note count (osu! only)
   */
  double speed_note_count;
  /**
   * Difficult aim strain count (osu! only)
   */
  double aim_difficult_strain_count;
  /**
   * Difficult speed strain count (osu! only)
   */
  double speed_difficult_strain_count;
  /**
   * Nested score per object (osu! only)
   */
  double nested_score_per_object;
  /**
   * Legacy score base multiplier (osu! only)
   */
  double legacy_score_base_multiplier;
  /**
   * Maximum legacy combo score (osu! only)
   */
  double maximum_legacy_combo_score;
  /**
   * Mono-stamina factor (taiko only)
   */
  double mono_stamina_factor;
  /**
   * Mechanical difficulty (taiko only)
   */
  double mechanical_difficulty;
  /**
   * Consistency factor (taiko only)
   */
  double consistency_factor;
  /**
   * Preempt value (catch only)
   */
  double preempt;
  /**
   * Number of fruits (catch only)
   */
  uint32_t n_fruits;
  /**
   * Number of droplets (catch only)
   */
  uint32_t n_droplets;
  /**
   * Number of tiny droplets (catch only)
   */
  uint32_t n_tiny_droplets;
  /**
   * Number of hold notes (mania only)
   */
  uint32_t n_hold_notes;
  /**
   * Whether this is a converted map
   */
  bool is_convert;
} rosu_pp_DifficultyAttributes;

/**
 * Unified performance attributes for all osu! game modes.
 *
 * Contains the total pp and breakdown by category, along with the underlying
 * difficulty attributes. Inspect `difficulty.mode` to determine which fields
 * are valid.
 */
typedef struct rosu_pp_PerformanceAttributes {
  /**
   * Total performance points
   */
  double pp;
  /**
   * Performance points from accuracy
   */
  double pp_acc;
  /**
   * Performance points from aim
   */
  double pp_aim;
  /**
   * Performance points from speed
   */
  double pp_speed;
  /**
   * Performance points from flashlight (osu! only)
   */
  double pp_flashlight;
  /**
   * Performance points from difficulty (taiko / mania)
   */
  double pp_difficulty;
  /**
   * Effective miss count (osu! only)
   */
  double effective_miss_count;
  /**
   * Speed deviation (osu! only)
   */
  double speed_deviation;
  /**
   * Combo-based estimated miss count (osu! only)
   */
  double combo_based_estimated_miss_count;
  /**
   * Score-based estimated miss count (osu! only)
   */
  double score_based_estimated_miss_count;
  /**
   * Estimated slider breaks for aim (osu! only)
   */
  double aim_estimated_slider_breaks;
  /**
   * Estimated slider breaks for speed (osu! only)
   */
  double speed_estimated_slider_breaks;
  /**
   * Estimated unstable rate (taiko only)
   */
  double estimated_unstable_rate;
  /**
   * Underlying difficulty attributes (mode-dependent)
   */
  struct rosu_pp_DifficultyAttributes difficulty;
} rosu_pp_PerformanceAttributes;

/**
 * Get the approach rate from the beatmap attributes.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesHandle` pointer (may be null).
 *
 * **Returns:** The approach rate value, or `0.0` if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesHandle`, or null.
 */
float rosu_pp_beatmap_attrs_ar(const struct rosu_pp_BeatmapAttributesHandle *handle);

/**
 * Create a new beatmap attributes builder with default settings.
 *
 * **Returns:** A non-null handle to a new `BeatmapAttributesBuilder`.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_beatmap_attrs_builder_free`.
 *
 * # Safety
 *
 * This function is safe to call from any context. It takes no raw pointer
 * arguments.
 */
struct rosu_pp_BeatmapAttributesBuilderHandle *rosu_pp_beatmap_attrs_builder_new(void);

/**
 * Turn the difficulty calculator into an inspector to view its configured
 * values.
 *
 * **Parameters:**
 * - `handle`: A `DifficultyHandle` pointer. **Consumed** by this call.
 *   The handle must NOT be used or freed after this call.
 *
 * **Returns:** A non-null `InspectDifficultyHandle` pointer on success, or
 * `NULL` if `handle` is null.
 *
 * **Ownership:** This function **consumes** the `difficulty` handle. The
 * caller must NOT call `rosu_pp_difficulty_free` on the handle, nor use it
 * after this call.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_inspect_difficulty_free`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 */
struct rosu_pp_InspectDifficultyHandle *rosu_pp_difficulty_inspect_new(struct rosu_pp_DifficultyHandle *handle);

/**
 * Load a beatmap from a file path.
 *
 * **Parameters:**
 * - `path`: Null-terminated C string containing the file path to the `.osu` file.
 * - `out`: Pointer to store the resulting `BeatmapHandle`.
 *
 * **Returns:**
 * - `FfiResult::Ok` — Success. `out` is set to a non-null handle (caller owns).
 * - `FfiResult::ParseError` — The path is invalid UTF-8 or the file could not
 *   be read or parsed. `out` is set to `NULL`.
 * - `FfiResult::NullPointer` — The `path` or `out` pointer is null.
 *
 * **Memory:** On `Ok`, the caller owns the handle written to `out` and must
 * free it with `rosu_pp_beatmap_free`.
 *
 * # Safety
 *
 * `path` must point to a valid null-terminated UTF-8 string, or be null.
 * `out` must point to a valid `*mut *mut BeatmapHandle` capable of receiving
 * the written pointer.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_from_path(const char *path, struct rosu_pp_BeatmapHandle * *out);

/**
 * Apply the clock rate to get adjusted AR and OD values.
 *
 * The returned struct has AR and OD adjusted for the clock rate, while CS
 * and HP remain unchanged (they are not affected by clock rate).
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesHandle` pointer (may be null).
 * - `out`: Pointer to an `AdjustedBeatmapAttributes` struct where results
 *   will be written (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` or `out` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesHandle`, or null.
 * `out` must point to a valid `AdjustedBeatmapAttributes` struct, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_attrs_apply_clock_rate(const struct rosu_pp_BeatmapAttributesHandle *handle, struct rosu_pp_AdjustedBeatmapAttributes *out);

/**
 * Create a new difficulty calculator with default settings.
 *
 * **Returns:** A non-null handle to a new `Difficulty` builder.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_difficulty_free`.
 *
 * # Safety
 *
 * This function is safe to call from any context. It takes no raw pointer
 * arguments.
 */
struct rosu_pp_DifficultyHandle *rosu_pp_difficulty_new(void);

/**
 * Create a new gradual difficulty calculator.
 *
 * **Parameters:**
 * - `difficulty`: A `DifficultyHandle` pointer. **Consumed** by this call.
 *   The caller must NOT use or free this handle afterward.
 * - `map`: A valid `BeatmapHandle` pointer (may be null).
 *
 * **Returns:** A non-null handle on success, or `NULL` if either pointer is null.
 *
 * **Ownership:** This function **consumes** the `difficulty` handle. The caller
 * must NOT call `rosu_pp_difficulty_free` on the difficulty handle, nor use it
 * after this call. The `map` handle is only borrowed and remains valid.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_gradual_difficulty_free`.
 *
 * # Safety
 *
 * `difficulty` must be a valid pointer to a `DifficultyHandle`, or null.
 * `map` must be a valid pointer to a `BeatmapHandle`, or null.
 */
struct rosu_pp_GradualDifficultyHandle *rosu_pp_gradual_difficulty_new(struct rosu_pp_DifficultyHandle *difficulty, const struct rosu_pp_BeatmapHandle *map);

/**
 * Create a new gradual performance calculator.
 *
 * **Parameters:**
 * - `difficulty`: A `DifficultyHandle` pointer. **Consumed** by this call.
 *   The caller must NOT use or free this handle afterward.
 * - `map`: A valid `BeatmapHandle` pointer (may be null).
 *
 * **Returns:** A non-null handle on success, or `NULL` if either pointer is null.
 *
 * **Ownership:** This function **consumes** the `difficulty` handle. The caller
 * must NOT call `rosu_pp_difficulty_free` on the difficulty handle, nor use it
 * after this call. The `map` handle is only borrowed and remains valid.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_gradual_performance_free`.
 *
 * # Safety
 *
 * `difficulty` must be a valid pointer to a `DifficultyHandle`, or null.
 * `map` must be a valid pointer to a `BeatmapHandle`, or null.
 */
struct rosu_pp_GradualPerformanceHandle *rosu_pp_gradual_performance_new(struct rosu_pp_DifficultyHandle *difficulty, const struct rosu_pp_BeatmapHandle *map);

/**
 * Get the overall difficulty from the beatmap attributes.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesHandle` pointer (may be null).
 *
 * **Returns:** The overall difficulty value, or `0.0` if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesHandle`, or null.
 */
float rosu_pp_beatmap_attrs_od(const struct rosu_pp_BeatmapAttributesHandle *handle);

/**
 * Populate the builder from a beatmap's attributes (AR, OD, CS, HP, mode,
 * convert status).
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesBuilderHandle` pointer (may be null).
 * - `map`: A valid `BeatmapHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * either pointer is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call. Individual
 * setters (ar, od, cs, hp) can be called after `map` to override specific
 * values.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesBuilderHandle`, or null.
 * `map` must be a valid pointer to a `BeatmapHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_attrs_builder_map(struct rosu_pp_BeatmapAttributesBuilderHandle *handle, const struct rosu_pp_BeatmapHandle *map);

/**
 * Parse a mod string from acronyms (e.g., `"HR"`, `"HDhtFLwG"`).
 *
 * Parses a concatenated string of mod acronyms and returns a handle to the
 * resulting mods collection.
 *
 * **Parameters:**
 * - `s`: Null-terminated C string containing mod acronyms.
 * - `out`: Pointer to store the resulting `ModsHandle`.
 *
 * **Returns:** `FfiResult::Ok` on success, `FfiResult::ParseError` if the
 * string is not valid UTF-8, or `FfiResult::NullPointer` if `s` or `out`
 * is null.
 *
 * **Memory:** The caller owns the handle written to `out` and must free it
 * with `rosu_pp_mods_free`.
 *
 * # Safety
 *
 * `s` must point to a valid null-terminated UTF-8 string, or be null.
 * `out` must point to a valid `*mut *mut ModsHandle` capable of receiving the
 * written pointer.
 */
enum rosu_pp_FfiResult rosu_pp_mods_from_acronym(const char *s, struct rosu_pp_ModsHandle * *out);

/**
 * Inspect the mods configured on a difficulty calculator.
 *
 * **Parameters:**
 * - `handle`: A valid `InspectDifficultyHandle` pointer (may be null).
 *
 * **Returns:** A `ModsHandle` pointer on success, or `NULL` if `handle` is
 * null.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_mods_free`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to an `InspectDifficultyHandle`, or null.
 */
struct rosu_pp_ModsHandle *rosu_pp_inspect_difficulty_mods(const struct rosu_pp_InspectDifficultyHandle *handle);

/**
 * Clone a difficulty calculator handle.
 *
 * Creates an independent copy of the difficulty builder, including all
 * configured settings (mods, passed_objects, clock_rate, attribute overrides,
 * etc.).
 *
 * **Parameters:**
 * - `handle`: A valid `DifficultyHandle` pointer (may be null).
 *
 * **Returns:** A new handle on success, or `NULL` if `handle` is null.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_difficulty_free`. The original `handle` remains valid.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 */
struct rosu_pp_DifficultyHandle *rosu_pp_difficulty_clone(const struct rosu_pp_DifficultyHandle *handle);

/**
 * Create a new performance calculator for the given beatmap.
 *
 * Difficulty attributes will be calculated internally from the beatmap,
 * which is a costly operation. For better performance when calculating
 * performance for the same map multiple times, consider using
 * `rosu_pp_performance_new_from_diff_attrs` or
 * `rosu_pp_performance_new_from_attrs` with pre-calculated attributes.
 *
 * **Parameters:**
 * - `map`: A valid `BeatmapHandle` pointer (may be null).
 *
 * **Returns:** A non-null handle on success, or `NULL` if `map` is null.
 *
 * **Lifetime requirement:** The `map` handle **must remain valid** for the
 * entire lifetime of the returned `PerformanceHandle`. Do NOT call
 * `rosu_pp_beatmap_free` on the map handle until after you have called
 * `rosu_pp_performance_free`.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_performance_free`.
 *
 * # Safety
 *
 * `map` must be a valid pointer to a `BeatmapHandle`, or null.
 */
struct rosu_pp_PerformanceHandle *rosu_pp_performance_new(const struct rosu_pp_BeatmapHandle *map);

/**
 * Get the circle size from the beatmap attributes.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesHandle` pointer (may be null).
 *
 * **Returns:** The circle size value, or `0.0` if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesHandle`, or null.
 */
float rosu_pp_beatmap_attrs_cs(const struct rosu_pp_BeatmapAttributesHandle *handle);

/**
 * Convert a game mode to its string representation.
 *
 * **Parameters:**
 * - `mode`: A `GameMode` value.
 *
 * **Returns:** A pointer to a static null-terminated string:
 * - `Osu` -> `"osu"`
 * - `Taiko` -> `"taiko"`
 * - `Catch` -> `"catch"`
 * - `Mania` -> `"mania"`
 *
 * **Memory:** The returned pointer points to static data and does NOT need
 * to be freed.
 *
 * # Safety
 *
 * This function is safe to call from any context. It takes no raw pointer
 * arguments.
 */
const char *rosu_pp_mode_to_str(enum rosu_pp_GameMode mode);

/**
 * Process the next hit object and return incremental difficulty attributes.
 *
 * Call this function repeatedly until it returns `FfiResult::Done` (all objects processed).
 *
 * **Parameters:**
 * - `handle`: A valid `GradualDifficultyHandle` pointer (may be null).
 * - `out`: Pointer to a `DifficultyAttributes` struct where results will be
 *   written (may be null).
 *
 * **Returns:**
 * - `FfiResult::Ok` — More objects remain; call `next` again.
 * - `FfiResult::Done` — All objects have been processed. No more calls needed.
 * - `FfiResult::NullPointer` — `handle` or `out` is null.
 *
 * **Handle reuse:** The `handle` remains valid after `Ok` and can be used for
 * subsequent calls.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `GradualDifficultyHandle`, or null.
 * `out` must point to a valid `DifficultyAttributes` struct, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_gradual_difficulty_next(struct rosu_pp_GradualDifficultyHandle *handle, struct rosu_pp_DifficultyAttributes *out);

/**
 * Process the next hit object and return incremental performance attributes.
 *
 * Call this function repeatedly, passing the score state for each hit object
 * in order, until it returns `FfiResult::Done` (all objects processed).
 *
 * **Parameters:**
 * - `handle`: A valid `GradualPerformanceHandle` pointer (may be null).
 * - `state`: A reference to a `ScoreState` struct describing the current hit.
 *   (may be null)
 * - `out`: Pointer to a `PerformanceAttributes` struct where results will be
 *   written (may be null).
 *
 * **Returns:**
 * - `FfiResult::Ok` — More objects remain; call `next` again.
 * - `FfiResult::Done` — All objects have been processed. No more calls needed.
 * - `FfiResult::NullPointer` — `handle`, `state`, or `out` is null.
 *
 * **Handle reuse:** The `handle` remains valid after `Ok` and can be used for
 * subsequent calls.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `GradualPerformanceHandle`, or null.
 * `state` must be a valid pointer to a `ScoreState`, or null.
 * `out` must point to a valid `PerformanceAttributes` struct, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_gradual_performance_next(struct rosu_pp_GradualPerformanceHandle *handle, const struct rosu_pp_ScoreState *state, struct rosu_pp_PerformanceAttributes *out);

/**
 * Get the HP drain rate from the beatmap attributes.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesHandle` pointer (may be null).
 *
 * **Returns:** The HP drain rate value, or `0.0` if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesHandle`, or null.
 */
float rosu_pp_beatmap_attrs_hp(const struct rosu_pp_BeatmapAttributesHandle *handle);

/**
 * Override the approach rate.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesBuilderHandle` pointer (may be null).
 * - `ar`: The approach rate value.
 * - `fixed`: If `true`, the value is used as-is with no mod/clock-rate
 *   adjustment. If `false`, the value may be adjusted by mods and clock rate.
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesBuilderHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_attrs_builder_ar(struct rosu_pp_BeatmapAttributesBuilderHandle *handle, float ar, bool fixed);

/**
 * Load a beatmap from raw bytes.
 *
 * **Parameters:**
 * - `bytes`: Pointer to a buffer containing the `.osu` file contents.
 * - `len`: Length of the buffer in bytes.
 * - `out`: Pointer to store the resulting `BeatmapHandle`.
 *
 * **Returns:**
 * - `FfiResult::Ok` — Success. `out` is set to a non-null handle (caller owns).
 * - `FfiResult::ParseError` — The bytes could not be parsed as a valid beatmap.
 *   `out` is set to `NULL`.
 * - `FfiResult::NullPointer` — The `bytes` or `out` pointer is null.
 *
 * **Memory:** On `Ok`, the caller owns the handle written to `out` and must
 * free it with `rosu_pp_beatmap_free`. The `bytes` buffer is only borrowed
 * during this call and may be freed immediately after.
 *
 * # Safety
 *
 * `bytes` must point to a valid buffer of `len` bytes, or be null if `len` is
 * 0. `out` must point to a valid `*mut *mut BeatmapHandle` capable of receiving
 * the written pointer.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_from_bytes(const uint8_t *bytes, uintptr_t len, struct rosu_pp_BeatmapHandle * *out);

/**
 * Set the game mods for the difficulty calculation.
 *
 * **Parameters:**
 * - `handle`: A valid `DifficultyHandle` pointer (may be null).
 * - `mods`: A `ModsHandle` pointer containing the mods to apply (may be null
 *   to clear mods).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_difficulty_mods(struct rosu_pp_DifficultyHandle *handle, const struct rosu_pp_ModsHandle *mods);

/**
 * Create a new performance calculator from pre-calculated performance attributes.
 *
 * Use this when you already have `PerformanceAttributes` from a previous
 * calculation. The attributes are copied so the returned handle has **no
 * lifetime requirement** on any external resource.
 *
 * **Parameters:**
 * - `attrs`: A valid `PerformanceAttributes` struct (may be null).
 *
 * **Returns:** A non-null handle on success, or `NULL` if `attrs` is null.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_performance_free`.
 *
 * # Safety
 *
 * `attrs` must be a valid pointer to a `PerformanceAttributes` struct, or null.
 */
struct rosu_pp_PerformanceHandle *rosu_pp_performance_new_from_attrs(const struct rosu_pp_PerformanceAttributes *attrs);

/**
 * Create a new zero-initialized ScoreState.
 *
 * **Returns:** A `ScoreState` struct with all fields set to zero/false.
 *
 * Initialize the returned struct with the appropriate hit result counts
 * for the play being evaluated.
 *
 * # Safety
 *
 * This function is safe to call from any context. It takes no raw pointer
 * arguments.
 */
struct rosu_pp_ScoreState rosu_pp_score_state_new(void);

/**
 * Get the clock rate from the beatmap attributes.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesHandle` pointer (may be null).
 *
 * **Returns:** The clock rate value, or `0.0` if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesHandle`, or null.
 */
double rosu_pp_beatmap_attrs_clock_rate(const struct rosu_pp_BeatmapAttributesHandle *handle);

/**
 * Free a gradual difficulty calculator handle.
 *
 * **Parameters:**
 * - `handle`: A handle returned by `rosu_pp_gradual_difficulty_new`. May be
 *   null (null is a no-op).
 *
 * # Safety
 *
 * `handle` must be a null pointer, or a valid handle previously returned by
 * `rosu_pp_gradual_difficulty_new`.
 */
void rosu_pp_gradual_difficulty_free(struct rosu_pp_GradualDifficultyHandle *handle);

/**
 * Convert a string to a game mode.
 *
 * Accepts multiple string aliases for each mode:
 * - **osu!:** `"osu"`, `"std"`, `"0"`
 * - **taiko:** `"taiko"`, `"tko"`, `"1"`
 * - **catch:** `"catch"`, `"ctb"`, `"fruits"`, `"2"`
 * - **mania:** `"mania"`, `"mna"`, `"3"`
 *
 * **Parameters:**
 * - `s`: Null-terminated C string containing the mode name (may be null).
 * - `out`: Pointer to store the resulting `GameMode` (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, `FfiResult::InvalidArgument` if the
 * string doesn't match any known mode, or `FfiResult::NullPointer` if `s` or
 * `out` is null.
 *
 * # Safety
 *
 * `s` must point to a valid null-terminated UTF-8 string, or be null.
 * `out` must point to a valid `GameMode`, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_mode_from_str(const char *s, enum rosu_pp_GameMode *out);

/**
 * Parse a mod string from JSON with an explicit game mode.
 *
 * Parses a JSON-encoded mod specification and returns a handle to the
 * resulting mods collection specific to the given game mode.
 *
 * Example input:
 * - `"72"`
 * - `"[{\"acronym\":\"HD\"},{\"acronym\":\"DT\",\"settings\":{\"speed_change\":1.2}}]"`
 *
 * **Parameters:**
 * - `s`: Null-terminated C string containing the JSON-encoded mod specification.
 * - `deny_unknown_fields`: If `true`, parsing fails when unknown mod settings
 *   are encountered. If `false`, unknown settings are silently ignored.
 * - `mode`: The game mode to parse mods for (osu!, taiko, catch, or mania).
 * - `out`: Pointer to store the resulting `ModsHandle`.
 *
 * **Returns:** `FfiResult::Ok` on success, `FfiResult::ParseError` if the
 * string is not valid JSON or could not be parsed, or `FfiResult::NullPointer`
 * if `s` or `out` is null.
 *
 * **Memory:** The caller owns the handle written to `out` and must free it with
 * `rosu_pp_mods_free`.
 *
 * # Safety
 *
 * `s` must point to a valid null-terminated UTF-8 string, or be null.
 * `out` must point to a valid `*mut *mut ModsHandle` capable of receiving the
 * written pointer.
 */
enum rosu_pp_FfiResult rosu_pp_mods_from_json_with_mode(const char *s, bool deny_unknown_fields, enum rosu_pp_GameMode mode, struct rosu_pp_ModsHandle * *out);

/**
 * Free a gradual performance calculator handle.
 *
 * **Parameters:**
 * - `handle`: A handle returned by `rosu_pp_gradual_performance_new`. May be
 *   null (null is a no-op).
 *
 * # Safety
 *
 * `handle` must be a null pointer, or a valid handle previously returned by
 * `rosu_pp_gradual_performance_new`.
 */
void rosu_pp_gradual_performance_free(struct rosu_pp_GradualPerformanceHandle *handle);

/**
 * Override the overall difficulty.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesBuilderHandle` pointer (may be null).
 * - `od`: The overall difficulty value.
 * - `fixed`: If `true`, the value is used as-is with no mod/clock-rate
 *   adjustment. If `false`, the value may be adjusted by mods and clock rate.
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesBuilderHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_attrs_builder_od(struct rosu_pp_BeatmapAttributesBuilderHandle *handle, float od, bool fixed);

/**
 * Create a new performance calculator from pre-calculated difficulty attributes.
 *
 * Use this when you already have `DifficultyAttributes` from a previous
 * calculation. Performance points will be computed from the score parameters
 * set via setters.
 *
 * The attributes are copied so the returned handle has **no lifetime requirement**
 * on any external resource.
 *
 * **Parameters:**
 * - `attrs`: A valid `DifficultyAttributes` struct (may be null).
 *
 * **Returns:** A non-null handle on success, or `NULL` if `attrs` is null.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_performance_free`.
 *
 * # Safety
 *
 * `attrs` must be a valid pointer to a `DifficultyAttributes` struct, or null.
 */
struct rosu_pp_PerformanceHandle *rosu_pp_performance_new_from_diff_attrs(const struct rosu_pp_DifficultyAttributes *attrs);

/**
 * Calculate the total number of hits from a score state for a given game mode.
 *
 * Adds up n300, n100, n50 (if not taiko), n_katu (if not osu/taiko),
 * and n_geki (if not osu/taiko/catch) to get the total hit count.
 *
 * **Parameters:**
 * - `state`: A valid `ScoreState` pointer (may be null).
 * - `mode`: The game mode (0=osu!, 1=taiko, 2=catch, 3=mania).
 *
 * **Returns:** The total number of hits, or 0 if `state` is null.
 *
 * # Safety
 *
 * `state` must be a valid pointer to a `ScoreState`, or null.
 */
uint32_t rosu_pp_score_state_total_hits(const struct rosu_pp_ScoreState *state, enum rosu_pp_GameMode mode);

/**
 * Calculate the AR and OD hit windows for the beatmap attributes.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesHandle` pointer (may be null).
 * - `out`: Pointer to a `HitWindows` struct where results will be written
 *   (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` or `out` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesHandle`, or null.
 * `out` must point to a valid `HitWindows` struct, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_attrs_hit_windows(const struct rosu_pp_BeatmapAttributesHandle *handle, struct rosu_pp_HitWindows *out);

/**
 * Free a strains handle and release its memory.
 *
 * **Parameters:**
 * - `handle`: A handle returned by `rosu_pp_difficulty_strains`. May be
 *   null (null is a no-op).
 *
 * # Safety
 *
 * `handle` must be a null pointer, or a valid handle previously returned by
 * `rosu_pp_difficulty_strains`.
 */
void rosu_pp_strains_free(struct rosu_pp_StrainsData *handle);

/**
 *  Amount of passed objects for partial plays, e.g. a fail.
 *
 *  **Parameters:**
 *    - `passed_objects`: The number of hit objects to consider.
 *   - `handle`: A valid `DifficultyHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_difficulty_passed_objects(struct rosu_pp_DifficultyHandle *handle, uint32_t passed_objects);

/**
 * Override the circle size.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesBuilderHandle` pointer (may be null).
 * - `cs`: The circle size value.
 * - `fixed`: If `true`, the value is used as-is with no mod/clock-rate
 *   adjustment. If `false`, the value may be adjusted by mods and clock rate.
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesBuilderHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_attrs_builder_cs(struct rosu_pp_BeatmapAttributesBuilderHandle *handle, float cs, bool fixed);

/**
 *  Adjust the clock rate used in the calculation.
 *
 *  If none is specified, it will take the clock rate based on the mods
 *  i.e. 1.5 for DT, 0.75 for HT and 1.0 otherwise.
 *
 *  **Parameters:**
 *    - `clock_rate`: The clock rate multiplier (must be positive).
 *   - `handle`: A valid `DifficultyHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_difficulty_clock_rate(struct rosu_pp_DifficultyHandle *handle, double clock_rate);

/**
 * Inspect a value from the difficulty calculator.
 *
 * **Parameters:**
 * - `handle`: A valid `InspectDifficultyHandle` pointer (may be null).
 * - `out`: Pointer to store the inspected value (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` or `out` is null, or `FfiResult::None` if the value is
 * not available.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to an `InspectDifficultyHandle`, or null.
 * `out` must point to a valid `$ty`, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_inspect_difficulty_passed_objects(const struct rosu_pp_InspectDifficultyHandle *handle, uint32_t *out);

/**
 * Returns the value of the `$field` field from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The field value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
int32_t rosu_pp_beatmap_version(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Inspect a value from the difficulty calculator.
 *
 * **Parameters:**
 * - `handle`: A valid `InspectDifficultyHandle` pointer (may be null).
 * - `out`: Pointer to store the inspected value (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` or `out` is null, or `FfiResult::None` if the value is
 * not available.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to an `InspectDifficultyHandle`, or null.
 * `out` must point to a valid `$ty`, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_inspect_difficulty_clock_rate(const struct rosu_pp_InspectDifficultyHandle *handle, double *out);

/**
 * Set the game mods for the performance calculation.
 *
 * **Parameters:**
 * - `handle`: A valid `PerformanceHandle` pointer (may be null).
 * - `mods`: A `ModsHandle` pointer containing the mods to apply (may be null
 *   to clear mods).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_mods(struct rosu_pp_PerformanceHandle *handle, const struct rosu_pp_ModsHandle *mods);

/**
 * Free a beatmap attributes handle and release its memory.
 *
 * **Parameters:**
 * - `handle`: A handle returned by `rosu_pp_beatmap_attrs_builder_build`.
 *   May be null (null is a no-op).
 *
 * After calling this function, the handle must NOT be used again.
 *
 * # Safety
 *
 * `handle` must be a null pointer, or a valid handle previously returned by
 * `rosu_pp_beatmap_attrs_builder_build`.
 */
void rosu_pp_beatmap_attrs_free(struct rosu_pp_BeatmapAttributesHandle *handle);

/**
 * Returns a computed value derived from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The computed value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
enum rosu_pp_GameMode rosu_pp_beatmap_mode(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Inspect a value from the difficulty calculator.
 *
 * **Parameters:**
 * - `handle`: A valid `InspectDifficultyHandle` pointer (may be null).
 * - `out`: Pointer to store the inspected value (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` or `out` is null, or `FfiResult::None` if the value is
 * not available.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to an `InspectDifficultyHandle`, or null.
 * `out` must point to a valid `$ty`, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_inspect_difficulty_hardrock_offsets(const struct rosu_pp_InspectDifficultyHandle *handle, bool *out);

/**
 * Returns the value of the `$field` field from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The field value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
float rosu_pp_beatmap_ar(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Inspect a value from the difficulty calculator.
 *
 * **Parameters:**
 * - `handle`: A valid `InspectDifficultyHandle` pointer (may be null).
 * - `out`: Pointer to store the inspected value (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` or `out` is null, or `FfiResult::None` if the value is
 * not available.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to an `InspectDifficultyHandle`, or null.
 * `out` must point to a valid `$ty`, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_inspect_difficulty_lazer(const struct rosu_pp_InspectDifficultyHandle *handle, bool *out);

/**
 * Returns the value of the `$field` field from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The field value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
float rosu_pp_beatmap_cs(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Inspect a beatmap attribute from the difficulty calculator.
 *
 * **Parameters:**
 * - `handle`: A valid `InspectDifficultyHandle` pointer (may be null).
 * - `out`: Pointer to store the inspected value (may be null).
 * - `fixed`: Pointer to store whether the value is fixed (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if any pointer is null, or `FfiResult::None` if the value is not
 * available.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to an `InspectDifficultyHandle`, or null.
 * `out` must point to a valid `$ty`, or be null.
 * `fixed` must point to a valid `bool`, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_inspect_difficulty_ar(const struct rosu_pp_InspectDifficultyHandle *handle, float *out, bool *fixed);

/**
 * Returns the value of the `$field` field from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The field value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
float rosu_pp_beatmap_hp(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Inspect a beatmap attribute from the difficulty calculator.
 *
 * **Parameters:**
 * - `handle`: A valid `InspectDifficultyHandle` pointer (may be null).
 * - `out`: Pointer to store the inspected value (may be null).
 * - `fixed`: Pointer to store whether the value is fixed (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if any pointer is null, or `FfiResult::None` if the value is not
 * available.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to an `InspectDifficultyHandle`, or null.
 * `out` must point to a valid `$ty`, or be null.
 * `fixed` must point to a valid `bool`, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_inspect_difficulty_cs(const struct rosu_pp_InspectDifficultyHandle *handle, float *out, bool *fixed);

/**
 * Returns the value of the `$field` field from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The field value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
float rosu_pp_beatmap_od(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Inspect a beatmap attribute from the difficulty calculator.
 *
 * **Parameters:**
 * - `handle`: A valid `InspectDifficultyHandle` pointer (may be null).
 * - `out`: Pointer to store the inspected value (may be null).
 * - `fixed`: Pointer to store whether the value is fixed (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if any pointer is null, or `FfiResult::None` if the value is not
 * available.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to an `InspectDifficultyHandle`, or null.
 * `out` must point to a valid `$ty`, or be null.
 * `fixed` must point to a valid `bool`, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_inspect_difficulty_hp(const struct rosu_pp_InspectDifficultyHandle *handle, float *out, bool *fixed);

/**
 * Parse a mod string from JSON with automatic mode detection.
 *
 * Parses a JSON-encoded mod specification and infers the game mode from the
 * mod combinations. For example, `"FI"` (FadeIn) implies mania mode since it
 * is mania-specific.
 *
 * Example input:
 * - `"72"`
 * - `"[{\"acronym\":\"HD\"},{\"acronym\":\"DT\",\"settings\":{\"speed_change\":1.2}}]"`
 *
 * **Parameters:**
 * - `s`: Null-terminated C string containing the JSON-encoded mod specification.
 * - `deny_unknown_fields`: If `true`, parsing fails when unknown mod settings
 *   are encountered. If `false`, unknown settings are silently ignored.
 * - `out`: Pointer to store the resulting `ModsHandle`.
 *
 * **Returns:** `FfiResult::Ok` on success, `FfiResult::ParseError` if the
 * string is not valid JSON or could not be parsed, or `FfiResult::NullPointer`
 * if `s` or `out` is null.
 *
 * **Memory:** The caller owns the handle written to `out` and must free it with
 * `rosu_pp_mods_free`.
 *
 * # Safety
 *
 * `s` must point to a valid null-terminated UTF-8 string, or be null.
 * `out` must point to a valid `*mut *mut ModsHandle` capable of receiving the
 * written pointer.
 */
enum rosu_pp_FfiResult rosu_pp_mods_from_json(const char *s, bool deny_unknown_fields, struct rosu_pp_ModsHandle * *out);

/**
 * Returns the value of the `$field` field from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The field value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
double rosu_pp_beatmap_slider_multiplier(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Inspect a beatmap attribute from the difficulty calculator.
 *
 * **Parameters:**
 * - `handle`: A valid `InspectDifficultyHandle` pointer (may be null).
 * - `out`: Pointer to store the inspected value (may be null).
 * - `fixed`: Pointer to store whether the value is fixed (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if any pointer is null, or `FfiResult::None` if the value is not
 * available.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to an `InspectDifficultyHandle`, or null.
 * `out` must point to a valid `$ty`, or be null.
 * `fixed` must point to a valid `bool`, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_inspect_difficulty_od(const struct rosu_pp_InspectDifficultyHandle *handle, float *out, bool *fixed);

/**
 * Returns the value of the `$field` field from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The field value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
double rosu_pp_beatmap_slider_tick_rate(const struct rosu_pp_BeatmapHandle *handle);

/**
 *  Override the approach rate (AR).
 *
 *  Sets a fixed AR value, bypassing the normal AR calculation from the
 *  beatmap. If `fixed` is `true`, the value is used as-is. If `fixed` is
 *  `false`, the value may be adjusted by mods and clock rate.
 *
 *  **Parameters:**
 *    - `ar`: The approach rate value.
 *    - `fixed`: If `true`, the value is used as-is. If `false`, it may be
 *      adjusted by mods and clock rate.
 *   - `handle`: A valid `DifficultyHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_difficulty_ar(struct rosu_pp_DifficultyHandle *handle, float ar, bool fixed);

/**
 * Returns the value of the `$field` field from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The field value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
float rosu_pp_beatmap_stack_leniency(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Returns the value of the `$field` field from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The field value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
bool rosu_pp_beatmap_is_convert(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Returns a computed value derived from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The computed value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
uintptr_t rosu_pp_beatmap_hit_object_count(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Returns a computed value derived from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The computed value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
double rosu_pp_beatmap_total_break_time(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Returns a computed value derived from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The computed value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
double rosu_pp_beatmap_bpm(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Returns a computed value derived from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The computed value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
uintptr_t rosu_pp_beatmap_timing_point_count(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Returns a computed value derived from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The computed value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
uintptr_t rosu_pp_beatmap_difficulty_point_count(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Returns a computed value derived from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The computed value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
uintptr_t rosu_pp_beatmap_effect_point_count(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Returns a computed value derived from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The computed value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
uintptr_t rosu_pp_beatmap_break_count(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Returns a computed value derived from the beatmap.
 *
 * **Parameters:**
 * - `handle`: A valid beatmap handle pointer (may be null).
 *
 * **Returns:** The computed value, or the type's default value if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
uintptr_t rosu_pp_beatmap_hit_sound_count(const struct rosu_pp_BeatmapHandle *handle);

/**
 * Free an inspected difficulty handle.
 *
 * **Parameters:**
 * - `handle`: A handle returned by `rosu_pp_difficulty_inspect`. May be null
 *   (null is a no-op).
 *
 * # Safety
 *
 * `handle` must be a null pointer, or a valid handle previously returned by
 * `rosu_pp_difficulty_inspect_new`.
 */
void rosu_pp_inspect_difficulty_free(struct rosu_pp_InspectDifficultyHandle *handle);

/**
 *  Override the circle size (CS).
 *
 *  Sets a fixed CS value, bypassing the normal CS calculation from the
 *  beatmap. If `fixed` is `true`, the value is used as-is. If `fixed` is
 *  `false`, the value may be adjusted by mods.
 *
 *  **Parameters:**
 *    - `cs`: The circle size value.
 *    - `fixed`: If `true`, the value is used as-is. If `false`, it may be
 *      adjusted by mods.
 *   - `handle`: A valid `DifficultyHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_difficulty_cs(struct rosu_pp_DifficultyHandle *handle, float cs, bool fixed);

/**
 * Override the HP drain rate.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesBuilderHandle` pointer (may be null).
 * - `hp`: The HP drain rate value.
 * - `fixed`: If `true`, the value is used as-is with no mod/clock-rate
 *   adjustment. If `false`, the value may be adjusted by mods and clock rate.
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesBuilderHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_attrs_builder_hp(struct rosu_pp_BeatmapAttributesBuilderHandle *handle, float hp, bool fixed);

/**
 *  Override the HP drain rate.
 *
 *  Sets a fixed HP value, bypassing the normal HP calculation from the
 *  beatmap. If `fixed` is `true`, the value is used as-is. If `fixed` is
 *  `false`, the value may be adjusted by mods.
 *
 *  **Parameters:**
 *    - `hp`: The HP drain rate value.
 *    - `fixed`: If `true`, the value is used as-is. If `false`, it may be
 *      adjusted by mods.
 *   - `handle`: A valid `DifficultyHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_difficulty_hp(struct rosu_pp_DifficultyHandle *handle, float hp, bool fixed);

/**
 * Check whether the beatmap contains suspicious hit objects.
 *
 * Some beatmaps contain hit objects that appear too suspicious for further
 * calculation (e.g., maps designed to test the limits of osu!). This function
 * checks for such cases.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` if the map is safe to use, or
 * `FfiResult::TooSuspicious` if the map contains suspicious objects.
 * Returns `FfiResult::NullPointer` if `handle` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_check_suspicion(const struct rosu_pp_BeatmapHandle *handle);

/**
 *  Override the overall difficulty (OD).
 *
 *  Sets a fixed OD value, bypassing the normal OD calculation from the
 *  beatmap. If `fixed` is `true`, the value is used as-is. If `fixed` is
 *  `false`, the value may be adjusted by mods and clock rate.
 *
 *  **Parameters:**
 *    - `od`: The overall difficulty value.
 *    - `fixed`: If `true`, the value is used as-is. If `false`, it may be
 *      adjusted by mods and clock rate.
 *   - `handle`: A valid `DifficultyHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_difficulty_od(struct rosu_pp_DifficultyHandle *handle, float od, bool fixed);

/**
 *  Amount of passed objects for partial plays, e.g. a fail.
 *
 *  **Parameters:**
 *    - `passed_objects`: The number of hit objects to consider.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_passed_objects(struct rosu_pp_PerformanceHandle *handle, uint32_t passed_objects);

/**
 * Create a mods handle from legacy bitflags.
 *
 * Converts a u32 bitflag representation (as used by the osu! legacy API) into
 * a full mods handle. Unknown bits are silently dropped.
 *
 * **Parameters:**
 * - `bits`: Legacy bitflag value representing the mods.
 *
 * **Returns:** A non-null `ModsHandle` pointer.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_mods_free`.
 *
 * # Safety
 *
 * This function is safe to call from any context. It takes no raw pointer
 * arguments.
 */
struct rosu_pp_ModsHandle *rosu_pp_mods_from_bits(uint32_t bits);

/**
 * Set the game mods for the beatmap attributes calculation.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesBuilderHandle` pointer (may be null).
 * - `mods`: A `ModsHandle` pointer containing the mods to apply (may be null
 *   to clear mods).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesBuilderHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_attrs_builder_mods(struct rosu_pp_BeatmapAttributesBuilderHandle *handle, const struct rosu_pp_ModsHandle *mods);

/**
 *  Adjust the clock rate used in the calculation.
 *
 *  If none is specified, it will take the clock rate based on the mods
 *  i.e. 1.5 for DT, 0.75 for HT and 1.0 otherwise.
 *
 *  **Parameters:**
 *    - `clock_rate`: The clock rate multiplier (must be positive).
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_clock_rate(struct rosu_pp_PerformanceHandle *handle, double clock_rate);

/**
 * Free a beatmap handle and release its memory.
 *
 * **Parameters:**
 * - `handle`: A handle returned by `rosu_pp_beatmap_from_path` or
 *   `rosu_pp_beatmap_from_bytes`. May be null (null is a no-op).
 *
 * After calling this function, the handle must NOT be used again.
 *
 * # Safety
 *
 * `handle` must be a null pointer, or a valid handle previously returned by
 * `rosu_pp_beatmap_from_path` or `rosu_pp_beatmap_from_bytes`.
 */
void rosu_pp_beatmap_free(struct rosu_pp_BeatmapHandle *handle);

/**
 *  Adjust patterns as if the HR mod is enabled.
 *
 *  Only relevant for osu!catch.
 *
 *  **Parameters:**
 *    - `hardrock_offsets`: Whether to apply hardrock-specific offsets.
 *   - `handle`: A valid `DifficultyHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_difficulty_hardrock_offsets(struct rosu_pp_DifficultyHandle *handle, bool hardrock_offsets);

/**
 * Convert a mods handle to legacy bitflags.
 *
 * **Parameters:**
 * - `mods`: A valid `ModsHandle` pointer (may be null).
 *
 * **Returns:** A u32 bitflag value representing the mods, or 0 if `mods` is null.
 *
 * # Safety
 *
 * `mods` must be a valid pointer to a `ModsHandle`, or null.
 */
uint32_t rosu_pp_mods_to_bits(const struct rosu_pp_ModsHandle *mods);

/**
 *  Override the approach rate (AR).
 *
 *  Sets a fixed AR value, bypassing the normal AR calculation from the
 *  beatmap. If `fixed` is `true`, the value is used as-is. If `fixed` is
 *  `false`, the value may be adjusted by mods and clock rate.
 *
 *  **Parameters:**
 *    - `ar`: The approach rate value.
 *    - `fixed`: If `true`, the value is used as-is. If `false`, it may be
 *      adjusted by mods and clock rate.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_ar(struct rosu_pp_PerformanceHandle *handle, float ar, bool fixed);

/**
 *  Whether the calculated attributes belong to an osu!lazer or osu!stable
 *  score.
 *
 *  **Parameters:**
 *    - `lazer`: Whether to use lazer mode calculation.
 *   - `handle`: A valid `DifficultyHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_difficulty_lazer(struct rosu_pp_DifficultyHandle *handle, bool lazer);

/**
 *  Override the circle size (CS).
 *
 *  Sets a fixed CS value, bypassing the normal CS calculation from the
 *  beatmap. If `fixed` is `true`, the value is used as-is. If `fixed` is
 *  `false`, the value may be adjusted by mods.
 *
 *  **Parameters:**
 *    - `cs`: The circle size value.
 *    - `fixed`: If `true`, the value is used as-is. If `false`, it may be
 *      adjusted by mods.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_cs(struct rosu_pp_PerformanceHandle *handle, float cs, bool fixed);

/**
 * Set a custom clock rate.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesBuilderHandle` pointer (may be null).
 * - `clock_rate`: The clock rate value.
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesBuilderHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_attrs_builder_clock_rate(struct rosu_pp_BeatmapAttributesBuilderHandle *handle, double clock_rate);

/**
 * Convert a mods handle to a string representation.
 *
 * Returns the mod acronyms as a string (e.g., `"HDHRDT"`).
 *
 * **Parameters:**
 * - `mods`: A valid `ModsHandle` pointer (may be null).
 *
 * **Returns:** A null-terminated C string on success, or `NULL` if `mods` is null.
 *
 * **Memory:** The caller **owns** the returned string and must free it using
 * `rosu_pp_mods_free_string`. Do NOT use standard `free()` on this pointer.
 *
 * # Safety
 *
 * `mods` must be a valid pointer to a `ModsHandle`, or null.
 */
char *rosu_pp_mods_to_string(const struct rosu_pp_ModsHandle *mods);

/**
 *  Override the HP drain rate.
 *
 *  Sets a fixed HP value, bypassing the normal HP calculation from the
 *  beatmap. If `fixed` is `true`, the value is used as-is. If `fixed` is
 *  `false`, the value may be adjusted by mods.
 *
 *  **Parameters:**
 *    - `hp`: The HP drain rate value.
 *    - `fixed`: If `true`, the value is used as-is. If `false`, it may be
 *      adjusted by mods.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_hp(struct rosu_pp_PerformanceHandle *handle, float hp, bool fixed);

/**
 * Calculate difficulty attributes for the configured settings.
 *
 * **Parameters:**
 * - `handle`: A valid `DifficultyHandle` pointer (may be null).
 * - `map`: A valid `BeatmapHandle` pointer (may be null).
 * - `out`: Pointer to a `DifficultyAttributes` struct where results will be written.
 *   (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle`, `map`, or `out` is null.
 *
 * **Ownership:** This function **does not** consume the `handle`. The caller
 * must STILL call `rosu_pp_difficulty_free` on the handle.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 * `map` must be a valid pointer to a `BeatmapHandle`, or null.
 * `out` must point to a valid `DifficultyAttributes` struct, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_difficulty_calculate(struct rosu_pp_DifficultyHandle *handle, const struct rosu_pp_BeatmapHandle *map, struct rosu_pp_DifficultyAttributes *out);

/**
 *  Override the overall difficulty (OD).
 *
 *  Sets a fixed OD value, bypassing the normal OD calculation from the
 *  beatmap. If `fixed` is `true`, the value is used as-is. If `fixed` is
 *  `false`, the value may be adjusted by mods and clock rate.
 *
 *  **Parameters:**
 *    - `od`: The overall difficulty value.
 *    - `fixed`: If `true`, the value is used as-is. If `false`, it may be
 *      adjusted by mods and clock rate.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_od(struct rosu_pp_PerformanceHandle *handle, float od, bool fixed);

/**
 * Set the game mode and convert status.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesBuilderHandle` pointer (may be null).
 * - `mode`: The game mode.
 * - `is_convert`: Whether this is a converted map.
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesBuilderHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_attrs_builder_mode(struct rosu_pp_BeatmapAttributesBuilderHandle *handle, enum rosu_pp_GameMode mode, bool is_convert);

/**
 * Free a string returned by `rosu_pp_mods_to_string`.
 *
 * **Parameters:**
 * - `s`: A string returned by `rosu_pp_mods_to_string`. May be null (null is
 *   a no-op).
 *
 * **Note:** This is the ONLY correct way to free strings from `mods_to_string`.
 * Do NOT use standard C `free()` on this pointer.
 *
 * # Safety
 *
 * `s` must be a null pointer, or a string previously returned by
 * `rosu_pp_mods_to_string`.
 */
void rosu_pp_mods_free_string(char *s);

/**
 *  Adjust patterns as if the HR mod is enabled.
 *
 *  Only relevant for osu!catch.
 *
 *  **Parameters:**
 *    - `hardrock_offsets`: Whether to apply hardrock-specific offsets.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_hardrock_offsets(struct rosu_pp_PerformanceHandle *handle, bool hardrock_offsets);

/**
 *  Whether the calculated attributes belong to an osu!lazer or osu!stable
 *  score.
 *
 *  **Parameters:**
 *    - `lazer`: Whether to use lazer mode calculation.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_lazer(struct rosu_pp_PerformanceHandle *handle, bool lazer);

/**
 * Free a mods handle and release its memory.
 *
 * **Parameters:**
 * - `handle`: A handle returned by `rosu_pp_mods_from_acronym`,
 *   `rosu_pp_mods_from_json`, `rosu_pp_mods_from_json_with_mode`, or
 *   `rosu_pp_mods_from_bits`. May be null (null is a no-op).
 *
 * # Safety
 *
 * `handle` must be a null pointer, or a valid handle previously returned by
 * a mods constructor function.
 */
void rosu_pp_mods_free(struct rosu_pp_ModsHandle *handle);

/**
 * Calculate difficulty attributes for the configured settings after verifying
 * the map is not too suspicious.
 *
 * Same as `rosu_pp_difficulty_calculate` but checks the map for suspicious
 * hit objects first. If the map is too suspicious, returns `FfiResult::TooSuspicious`.
 *
 * **Parameters:**
 * - `handle`: A valid `DifficultyHandle` pointer (may be null).
 * - `map`: A valid `BeatmapHandle` pointer (may be null).
 * - `out`: Pointer to a `DifficultyAttributes` struct where results will be written.
 *   (may be null).
 *
 * **Returns:**
 * - `FfiResult::Ok` — Calculation succeeded.
 * - `FfiResult::TooSuspicious` — The map contains suspicious hit objects.
 * - `FfiResult::NullPointer` — `handle`, `map`, or `out` is null.
 *
 * **Ownership:** This function **does not** consume the `handle`. The caller
 * must STILL call `rosu_pp_difficulty_free` on the handle.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 * `map` must be a valid pointer to a `BeatmapHandle`, or null.
 * `out` must point to a valid `DifficultyAttributes` struct, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_difficulty_checked_calculate(struct rosu_pp_DifficultyHandle *handle, const struct rosu_pp_BeatmapHandle *map, struct rosu_pp_DifficultyAttributes *out);

/**
 *  Set the accuracy between `0.0` and `100.0`.
 *
 *  **Parameters:**
 *    - `accuracy`: The accuracy value (0.0–100.0).
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_accuracy(struct rosu_pp_PerformanceHandle *handle, double accuracy);

/**
 * Populate the builder from a difficulty calculator's settings.
 *
 * Copies the map difficulty attributes (AR, OD, CS, HP), mods, and clock
 * rate from the difficulty calculator.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesBuilderHandle` pointer (may be null).
 * - `difficulty`: A valid `DifficultyHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * either pointer is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesBuilderHandle`, or null.
 * `difficulty` must be a valid pointer to a `DifficultyHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_beatmap_attrs_builder_difficulty(struct rosu_pp_BeatmapAttributesBuilderHandle *handle, const struct rosu_pp_DifficultyHandle *difficulty);

/**
 *  Set the number of misses.
 *
 *  **Parameters:**
 *    - `misses`: The number of misses in the score.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_misses(struct rosu_pp_PerformanceHandle *handle, uint32_t misses);

/**
 *  Set the maximum combo achieved.
 *
 *  **Parameters:**
 *    - `combo`: The maximum combo achieved in the score.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_combo(struct rosu_pp_PerformanceHandle *handle, uint32_t combo);

/**
 *  Specify the amount of "large tick" hits.
 *
 *  Only relevant for osu!standard.
 *
 *  The meaning depends on the kind of score:
 *  - if set on osu!stable, this value is irrelevant and can be `0`
 *  - if set on osu!lazer *with* slider accuracy, this value is the amount
 *    of hit slider ticks and repeats
 *  - if set on osu!lazer *without* slider accuracy, this value is the
 *    amount of hit slider heads, ticks, and repeats
 *
 *  **Parameters:**
 *    - `large_tick_hits`: The number of large tick hits.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_large_tick_hits(struct rosu_pp_PerformanceHandle *handle, uint32_t large_tick_hits);

/**
 * Perform the difficulty calculation but instead of evaluating the skill
 * strains, return them as is. Suitable for plotting the difficulty of a map
 * over time.
 *
 * **Parameters:**
 * - `handle`: A `DifficultyHandle` pointer. **Consumed** by this call.
 *   The handle must NOT be used or freed after this call.
 * - `map`: A valid `BeatmapHandle` pointer (may be null).
 *
 * **Returns:** A non-null `StrainsHandle` on success, or `NULL` if either
 * pointer is null.
 *
 * **Ownership:** This function **does not** consume the `handle`. The caller
 * must STILL call `rosu_pp_difficulty_free` on the handle.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_strains_free`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `DifficultyHandle`, or null.
 * `map` must be a valid pointer to a `BeatmapHandle`, or null.
 */
struct rosu_pp_StrainsData *rosu_pp_difficulty_strains(struct rosu_pp_DifficultyHandle *handle, const struct rosu_pp_BeatmapHandle *map);

/**
 * Build the `BeatmapAttributes` from the configured builder.
 *
 * **Parameters:**
 * - `handle`: A valid `BeatmapAttributesBuilderHandle` pointer. **Consumed**
 *   by this call. The handle must NOT be used or freed after this call.
 *
 * **Returns:** A non-null `BeatmapAttributesHandle` on success, or `NULL` if
 * `handle` is null.
 *
 * **Ownership:** This function **consumes** the `handle`. The caller must NOT
 * call `rosu_pp_beatmap_attrs_free` on the builder handle, nor use it after
 * this call.
 *
 * **Memory:** The caller owns the returned handle and must free it with
 * `rosu_pp_beatmap_attrs_free`.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `BeatmapAttributesBuilderHandle`, or null.
 */
struct rosu_pp_BeatmapAttributesHandle *rosu_pp_beatmap_attrs_builder_build(struct rosu_pp_BeatmapAttributesBuilderHandle *handle);

/**
 *  Specify the amount of "small tick" hits.
 *
 *  Only relevant for osu!standard lazer scores without slider accuracy. In
 *  that case, this value is the amount of slider tail hits.
 *
 *  **Parameters:**
 *    - `small_tick_hits`: The number of small tick hits.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_small_tick_hits(struct rosu_pp_PerformanceHandle *handle, uint32_t small_tick_hits);

/**
 *  Specify the amount of hit slider ends.
 *
 *  Only relevant for osu!standard lazer scores with slider accuracy.
 *
 *  **Parameters:**
 *    - `slider_end_hits`: The number of slider end hits.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_slider_end_hits(struct rosu_pp_PerformanceHandle *handle, uint32_t slider_end_hits);

/**
 *  Specify the amount of 300s of a play.
 *
 *  **Parameters:**
 *    - `n300`: The number of 300-score hit results.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_n300(struct rosu_pp_PerformanceHandle *handle, uint32_t n300);

/**
 * Free a beatmap attributes builder handle and release its memory.
 *
 * **Parameters:**
 * - `handle`: A handle returned by `rosu_pp_beatmap_attrs_builder_new`.
 *   May be null (null is a no-op).
 *
 * **Note:** Do NOT call this function if the handle was passed to
 * `rosu_pp_beatmap_attrs_builder_build` — that function consumes the
 * builder handle.
 *
 * # Safety
 *
 * `handle` must be a null pointer, or a valid handle previously returned by
 * `rosu_pp_beatmap_attrs_builder_new`.
 */
void rosu_pp_beatmap_attrs_builder_free(struct rosu_pp_BeatmapAttributesBuilderHandle *handle);

/**
 * Free a difficulty calculator handle.
 *
 * **Parameters:**
 * - `handle`: A handle returned by `rosu_pp_difficulty_new` or
 *   `rosu_pp_difficulty_clone`. May be null (null is a no-op).
 *
 * **Note:** Do NOT call this function if the handle was passed to
 * `rosu_pp_difficulty_gradual_difficulty` or `rosu_pp_difficulty_inspect`
 * — those functions consume the handle.
 *
 * # Safety
 *
 * `handle` must be a null pointer, or a valid handle previously returned by
 * `rosu_pp_difficulty_new` or `rosu_pp_difficulty_clone`.
 */
void rosu_pp_difficulty_free(struct rosu_pp_DifficultyHandle *handle);

/**
 *  Specify the amount of 100s of a play.
 *
 *  **Parameters:**
 *    - `n100`: The number of 100-score hit results.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_n100(struct rosu_pp_PerformanceHandle *handle, uint32_t n100);

/**
 *  Specify the amount of 50s of a play.
 *
 *  **Parameters:**
 *    - `n50`: The number of 50-score hit results.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_n50(struct rosu_pp_PerformanceHandle *handle, uint32_t n50);

/**
 *  Specify the amount of gekis of a play.
 *
 *  Only relevant for osu!mania for which it repesents the
 *  amount of n320.
 *
 *  **Parameters:**
 *    - `n_geki`: The number of geki hits.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_n_geki(struct rosu_pp_PerformanceHandle *handle, uint32_t n_geki);

/**
 *  Specify the amount of katus of a play.
 *
 *  Only relevant for osu!catch for which it represents the amount of tiny
 *  droplet misses and osu!mania for which it repesents the amount of n200.
 *
 *  **Parameters:**
 *    - `n_katu`: The number of katu hits.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_n_katu(struct rosu_pp_PerformanceHandle *handle, uint32_t n_katu);

/**
 *  Specify the legacy total score.
 *
 *  Only relevant for osu!standard.
 *
 *  **Parameters:**
 *    - `legacy_total_score`: The legacy total score value.
 *   - `handle`: A valid `PerformanceHandle` pointer (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer`
 * if `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_legacy_total_score(struct rosu_pp_PerformanceHandle *handle, uint32_t legacy_total_score);

/**
 * Set the priority of hitresults when generating remaining hitresults.
 *
 * **Parameters:**
 * - `handle`: A valid `PerformanceHandle` pointer (may be null).
 * - `priority`: The hitresult priority: `0` for BestCase (prioritize good hitresults),
 *   `1` for WorstCase (prioritize bad hitresults).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` is null.
 *
 * **Handle reuse:** The `handle` remains valid after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_hitresult_priority(struct rosu_pp_PerformanceHandle *handle, uint32_t priority);

/**
 * Calculate performance attributes for the configured settings after verifying
 * the map is not too suspicious.
 *
 * Same as `rosu_pp_performance_calculate` but checks the map for suspicious
 * hit objects first. If the map is too suspicious, returns `FfiResult::TooSuspicious`.
 *
 * **Parameters:**
 * - `handle`: A valid `PerformanceHandle` pointer. **Consumed** by this call.
 *   The handle must NOT be used or freed after this call.
 * - `out`: Pointer to a `PerformanceAttributes` struct where results will be
 *   written (may be null).
 *
 * **Returns:**
 * - `FfiResult::Ok` — Calculation succeeded.
 * - `FfiResult::TooSuspicious` — The map contains suspicious hit objects.
 * - `FfiResult::NullPointer` — `handle` or `out` is null.
 *
 * **Ownership:** This function **consumes** the `handle`. The caller must NOT
 * call `rosu_pp_performance_free` on the handle, nor use it after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 * `out` must point to a valid `PerformanceAttributes` struct, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_checked_calculate(struct rosu_pp_PerformanceHandle *handle, struct rosu_pp_PerformanceAttributes *out);

/**
 * Set the full score state at once.
 *
 * This is an alternative to setting individual hit counts (n300, n100, etc.)
 * and combo. Use this when you have a complete `ScoreState` struct.
 *
 * **Parameters:**
 * - `handle`: A valid `PerformanceHandle` pointer (may be null).
 * - `state`: A reference to a `ScoreState` struct with the score data. (may be
 *   null)
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` or `state` is null.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 * `state` must be a valid pointer to a `ScoreState`, or null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_state(struct rosu_pp_PerformanceHandle *handle, const struct rosu_pp_ScoreState *state);

/**
 * Calculate performance attributes for the configured settings.
 *
 * **Parameters:**
 * - `handle`: A valid `PerformanceHandle` pointer. **Consumed** by this call.
 *   The handle must NOT be used or freed after this call.
 * - `out`: Pointer to a `PerformanceAttributes` struct where results will be
 *   written (may be null).
 *
 * **Returns:** `FfiResult::Ok` on success, or `FfiResult::NullPointer` if
 * `handle` or `out` is null.
 *
 * **Ownership:** This function **consumes** the `handle`. The caller must NOT
 * call `rosu_pp_performance_free` on the handle, nor use it after this call.
 *
 * # Safety
 *
 * `handle` must be a valid pointer to a `PerformanceHandle`, or null.
 * `out` must point to a valid `PerformanceAttributes` struct, or be null.
 */
enum rosu_pp_FfiResult rosu_pp_performance_calculate(struct rosu_pp_PerformanceHandle *handle, struct rosu_pp_PerformanceAttributes *out);

/**
 * Free a performance calculator handle.
 *
 * **Parameters:**
 * - `handle`: A handle returned by `rosu_pp_performance_new`. May be null
 *   (null is a no-op).
 *
 * **Note:** Do NOT call this function if the handle was passed to
 * `rosu_pp_performance_calculate` — that function consumes the handle.
 *
 * # Safety
 *
 * `handle` must be a null pointer, or a valid handle previously returned by
 * `rosu_pp_performance_new`.
 */
void rosu_pp_performance_free(struct rosu_pp_PerformanceHandle *handle);
